import type { Metadata, Viewport } from "next";
import "@/styles/globals.css";
import { satoshi } from "@/styles/fonts";
import TopBanner from "@/components/layout/Banner/TopBanner";
import TopNavbar from "@/components/layout/Navbar/TopNavbar";
import Footer from "@/components/layout/Footer";
import HolyLoader from "holy-loader";
import Providers from "./providers";
import BuildTimer from "@/components/ui/BuildTimer";
import { ToastProvider } from "@/components/ui/Toast";

export const metadata: Metadata = {
  title: "Tahir Zai",
  description: "Generated by Fahad Abdul Qayyum",
};

export const viewport: Viewport = {
  themeColor: "#000000",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={satoshi.className}>
        <ToastProvider>
          <HolyLoader color="#868686" />
          <TopBanner />
          <Providers>
            <TopNavbar />
            {children}
          </Providers>
          <Footer />
          <BuildTimer />
        </ToastProvider>
      </body>
    </html>
  );
}
